language: node_js
node_js:
  # - 0.16.1
env:
- [
    {secure: ""},
    {secure: ""}
  ]
script:
# - "node tests/*.js"
# - whereis google-chrome-stable
# - whereis ChromeDriver
 - nvm ls-remote
 
addons: # get google-chrome-stable
  chrome: stable

install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  # - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  # - unzip ~/chromedriver_linux64.zip -d ~/
  # - rm ~/chromedriver_linux64.zip
  # - sudo mv -f ~/chromedriver /usr/local/share/
  # - sudo chmod +x /usr/local/share/chromedriver
  # - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  # - npm install -g mocha
  # - npm install -g chai
  # - npm install -g chai-as-promised
  # - npm install -g selenium-webdriver
  # - npm install -g geckodriver
