version: '3'
services:
        web:
                build: 
                        context: .
                        args:
                                - WATCHED_BRANCH=master
                ports:
                        - "4000:80"
                env_file:
                        - ./setup_env.env
